### ISSUE TITLE
Failed to require config

### ISSUE THREAD

**Issue by makipogz** [rem-bot-industries/rem-v2#213]
hi. this is my first time using rem as selfhost. and i am having issues with running the bot. i followed the instructions that stated in the read me but it gives me error in main.json. there myght be something wrong in my config but i didn't know how to deal with json error. here is the log

> 2018-02-05T15:13:40.431Z - error:  SyntaxError: E:\REM\config\main.json: Unexpected string in JSON at position 715
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:679:27)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at loadConfig (E:\REM\node_modules\docker-config-loader\index.js:19:18)
    at Object.<anonymous> (E:\REM\src\index.js:30:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
2018-02-05T15:13:40.453Z - error: Failed to require config!

**Comment by DasWolke** [comment]
Your config does not seem to be a proper json file.
