### ISSUE TITLE
Rem Weird Error

### ISSUE THREAD

**Issue by Mooseca** [rem-bot-industries/rem-v2#217]
I know you don't work on this anymore, and I have been self-hosting since u shut it down successfully until about a month ago where I started to receive errors when playing songs. After a few days of not being able to get rid of it successfully I decided to reinstall everything including my hosted server and I can't seem to get rid of this error no matter what I do. If you can help I would really appreciate it.

```
`error: Unhandled rejection: TypeError: this.setMaxListeners is not a function - Promise {
  <rejected> TypeError: this.setMaxListeners is not a function
    at new LangManager (/root/rem-v2/src/modules/managed/langManager.js:16:14)
    at ModuleManager.instantiateMod (/root/rem-v2/src/modules/moduleManager.js:108:27)
    at /root/rem-v2/src/modules/moduleManager.js:94:26
    at Promise._execute (/root/rem-v2/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/root/rem-v2/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/root/rem-v2/node_modules/bluebird/js/release/promise.js:79:10)
    at ModuleManager.load (/root/rem-v2/src/modules/moduleManager.js:80:16)
    at async.eachSeries (/root/rem-v2/src/modules/moduleManager.js:55:26)
    at /root/rem-v2/node_modules/async/dist/async.js:3096:16
    at replenish (/root/rem-v2/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/root/rem-v2/node_modules/async/dist/async.js:983:17)
    at /root/rem-v2/node_modules/async/dist/async.js:958:16
    at that.load.then.loadedMod (/root/rem-v2/src/modules/moduleManager.js:57:25)
    at tryCatcher (/root/rem-v2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/rem-v2/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/rem-v2/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/rem-v2/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/rem-v2/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/root/rem-v2/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/root/rem-v2/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/root/rem-v2/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
---------------------------------------------
    at Object.<anonymous> (/root/rem-v2/src/shardStarter.js:53:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3 }
`
```

**Comment by DasWolke** [comment]
Fixed the issue, was caused by using a function which is not supposed to be used anymore :)
